### ISSUE TITLE
Upstream to RustCrypto?

### ISSUE THREAD

**Issue by tarcieri** [sebastinas/ascon-aead#5]
Hi, I'm writing on behalf of the @RustCrypto organization.

We recently upstreamed the 6-year-old `ascon` crate:

https://github.com/RustCrypto/sponges/tree/master/ascon

When I went to split out the AEAD functionality into an `ascon-aead` crate I discovered your implementation, which looks much more complete (especially including the `ascon-hash` crate).

Would you be interested in upstreaming your work to the @RustCrypto project?

**Comment by sebastinas** [comment]
While this sounds interesting, it is unclear to me what that would mean for the future development of `ascon-core`, `ascon-hash` and `ascon-aead`. Would all those crates move to the @RustCrypto repositories? Would I be able to push code there? Who would be able to release the crates on crates.io?

**Comment by tarcieri** [comment]
We can get you access to the relevant repos which would also allow you to publish crates. It'd also mean you'd have access to the `ascon` crate.

The code would move there, but we can help implement the @RustCrypto traits from e.g. the `aead` and `digest` crates, and keep the crates updated as those APIs evolve.

**Comment by sebastinas** [comment]
That sounds good. Let's do it. What are the next steps to get it done?
